import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/* Generated by Together */

/**
 * This class represents the interactive interface to PACSUS administration functions carried
 * out in the Estates and Campus Services Office.  Information about these functions is in the
 * Administration use case diagram (hyperlinked from this class).
 *
 * The interface comprises one screen with all the functions present on it: they could all be on
 * view at once, or perhaps in alternative JPanels (in a JFrame with JTabbedPane); the current
 * date (day number) is always displayed.
 *
 * There could be any number of instances of this class, potentially one for each workstation
 * in the office, with different staff carrying different functions.
 *
 * The class implements Observer, and observes the system status so that it can keep the displayed current date correct.
 * @stereotype boundary
 */
@SuppressWarnings({ "deprecation", "serial", "unused"})
public class Administration_office extends JFrame implements Observer, ActionListener {
    /**
     * Each instance of Administration_office has a navigable association to the permit list so
     * that it can enquire about/add/delete/modify permits.
     * @supplierCardinality 1
     * @clientCardinality 1..*
     * @label Administration functions
     * @directed
     */
    
	private Permit_list lnkPermit_list;

    /**
     * Each instance of Administration_office has a navigable association to the vehicle list so
     * that it can enquire about/add/delete/modify vehicle details.
     * @clientCardinality 1..*
     * @supplierCardinality 1
     * @label Administration functions
     * @directed
     */
    private Vehicle_list lnkVehicle_list;

    /**
     * Each instance of Administration_office has a navigable association to the system status so
     * that it can find out status information about the system.
     * @clientCardinality 1..*
     * @supplierCardinality 1
     * @label See date
     * @directed
     */
    private System_status lnkSystem_status;
    
    private JPanel contentPane;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_2;
	private JTextField textField_3;
	private JTextField textField_4;
	private JTextField textField_5;
	private JTextField textField_6;
	private JTextField textField_7;
	private JTextField textField_8;
	private JTextField textField_9;
    private JTextField textField_10;
    
    private JTextField textField_11;
	private JTextField textField_12;
	private JTextField textField_13;
	private JTextField textField_14;
	private JTextField textField_15;
	private JTextField textField_16;
    private JTextField textField_17;
    
    public Administration_office(System_status status, Vehicle_list veh, Permit_list permits) {
    	this.lnkSystem_status = status;
    	this.lnkVehicle_list = veh;
    	this.lnkPermit_list = permits;
    	setTitle("Administration Office");
    	
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 750, 500);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new BorderLayout(0, 0));
		setContentPane(contentPane);
		
		JTabbedPane tabbedPane = new JTabbedPane(JTabbedPane.TOP);
		contentPane.add(tabbedPane, BorderLayout.CENTER);
		
		JPanel addPermit = new JPanel();
		tabbedPane.addTab("Add Permit", null, addPermit, null);
		GridBagLayout gbl_addPermit = new GridBagLayout();
		gbl_addPermit.columnWidths = new int[]{0, 0, 0, 0, 0, 0, 0, 0};
		gbl_addPermit.rowHeights = new int[] {30,30,30,30,30,30,30,30,30,30};
		gbl_addPermit.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, Double.MIN_VALUE};
		gbl_addPermit.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		addPermit.setLayout(gbl_addPermit);
		
		JLabel lblName = new JLabel("Name: ");
		GridBagConstraints gbc_lblName = new GridBagConstraints();
		gbc_lblName.anchor = GridBagConstraints.WEST;
		gbc_lblName.insets = new Insets(0, 0, 5, 5);
		gbc_lblName.gridx = 1;
		gbc_lblName.gridy = 0;
		addPermit.add(lblName, gbc_lblName);
		
		textField = new JTextField();
		GridBagConstraints gbc_textField = new GridBagConstraints();
		gbc_textField.insets = new Insets(0, 0, 5, 0);
		gbc_textField.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField.gridx = 6;
		gbc_textField.gridy = 0;
		addPermit.add(textField, gbc_textField);
		textField.setColumns(10);
		
		JLabel lblRegistrationNumber = new JLabel("Registration Number:");
		GridBagConstraints gbc_lblRegistrationNumber = new GridBagConstraints();
		gbc_lblRegistrationNumber.insets = new Insets(0, 0, 5, 5);
		gbc_lblRegistrationNumber.gridx = 1;
		gbc_lblRegistrationNumber.gridy = 1;
		addPermit.add(lblRegistrationNumber, gbc_lblRegistrationNumber);
		
		textField_1 = new JTextField();
		GridBagConstraints gbc_textField_1 = new GridBagConstraints();
		gbc_textField_1.insets = new Insets(0, 0, 5, 0);
		gbc_textField_1.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_1.gridx = 6;
		gbc_textField_1.gridy = 1;
		addPermit.add(textField_1, gbc_textField_1);
		textField_1.setColumns(10);
		
		JLabel lblCarMake = new JLabel("Car make:");
		GridBagConstraints gbc_lblCarMake = new GridBagConstraints();
		gbc_lblCarMake.insets = new Insets(0, 0, 5, 5);
		gbc_lblCarMake.anchor = GridBagConstraints.WEST;
		gbc_lblCarMake.gridx = 1;
		gbc_lblCarMake.gridy = 2;
		addPermit.add(lblCarMake, gbc_lblCarMake);
		
		textField_2 = new JTextField();
		GridBagConstraints gbc_textField_2 = new GridBagConstraints();
		gbc_textField_2.insets = new Insets(0, 0, 5, 0);
		gbc_textField_2.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_2.gridx = 6;
		gbc_textField_2.gridy = 2;
		addPermit.add(textField_2, gbc_textField_2);
		textField_2.setColumns(10);
		
		JLabel lblCarModel = new JLabel("Car model:");
		GridBagConstraints gbc_lblCarModel = new GridBagConstraints();
		gbc_lblCarModel.insets = new Insets(0, 0, 5, 5);
		gbc_lblCarModel.anchor = GridBagConstraints.WEST;
		gbc_lblCarModel.gridx = 1;
		gbc_lblCarModel.gridy = 3;
		addPermit.add(lblCarModel, gbc_lblCarModel);
		
		textField_3 = new JTextField();
		GridBagConstraints gbc_textField_3 = new GridBagConstraints();
		gbc_textField_3.insets = new Insets(0, 0, 5, 0);
		gbc_textField_3.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_3.gridx = 6;
		gbc_textField_3.gridy = 3;
		addPermit.add(textField_3, gbc_textField_3);
		textField_3.setColumns(10);
		
		JLabel lblCarColor = new JLabel("Car color:");
		GridBagConstraints gbc_lblCarColor = new GridBagConstraints();
		gbc_lblCarColor.insets = new Insets(0, 0, 5, 5);
		gbc_lblCarColor.anchor = GridBagConstraints.WEST;
		gbc_lblCarColor.gridx = 1;
		gbc_lblCarColor.gridy = 4;
		addPermit.add(lblCarColor, gbc_lblCarColor);
		
		textField_4 = new JTextField();
		GridBagConstraints gbc_textField_4 = new GridBagConstraints();
		gbc_textField_4.insets = new Insets(0, 0, 5, 0);
		gbc_textField_4.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_4.gridx = 6;
		gbc_textField_4.gridy = 4;
		addPermit.add(textField_4, gbc_textField_4);
		textField_4.setColumns(10);
		
		JLabel lblEnterPermitType = new JLabel("Enter Permit Type:");
		GridBagConstraints gbc_lblEnterPermitType = new GridBagConstraints();
		gbc_lblEnterPermitType.insets = new Insets(0, 0, 5, 5);
		gbc_lblEnterPermitType.anchor = GridBagConstraints.WEST;
		gbc_lblEnterPermitType.gridx = 1;
		gbc_lblEnterPermitType.gridy = 5;
		addPermit.add(lblEnterPermitType, gbc_lblEnterPermitType);
		
		JComboBox comboBox = new JComboBox();
		GridBagConstraints gbc_comboBox = new GridBagConstraints();
		gbc_comboBox.insets = new Insets(0, 0, 5, 0);
		gbc_comboBox.fill = GridBagConstraints.HORIZONTAL;
		gbc_comboBox.gridx = 6;
		gbc_comboBox.gridy = 5;
		addPermit.add(comboBox, gbc_comboBox);
		
		JLabel lblVisitDate = new JLabel("Visit Date:");
		GridBagConstraints gbc_lblVisitDate = new GridBagConstraints();
		gbc_lblVisitDate.insets = new Insets(0, 0, 5, 5);
		gbc_lblVisitDate.anchor = GridBagConstraints.WEST;
		gbc_lblVisitDate.gridx = 1;
		gbc_lblVisitDate.gridy = 6;
		addPermit.add(lblVisitDate, gbc_lblVisitDate);
		
		textField_5 = new JTextField();
		GridBagConstraints gbc_textField_5 = new GridBagConstraints();
		gbc_textField_5.gridheight = 2;
		gbc_textField_5.insets = new Insets(0, 0, 5, 0);
		gbc_textField_5.fill = GridBagConstraints.BOTH;
		gbc_textField_5.gridx = 6;
		gbc_textField_5.gridy = 6;
		addPermit.add(textField_5, gbc_textField_5);
		textField_5.setColumns(10);
		
		JLabel lblHostName = new JLabel("Host Name:");
		GridBagConstraints gbc_lblHostName = new GridBagConstraints();
		gbc_lblHostName.insets = new Insets(0, 0, 5, 5);
		gbc_lblHostName.anchor = GridBagConstraints.WEST;
		gbc_lblHostName.gridx = 1;
		gbc_lblHostName.gridy = 8;
		addPermit.add(lblHostName, gbc_lblHostName);
		
		textField_6 = new JTextField();
		GridBagConstraints gbc_textField_6 = new GridBagConstraints();
		gbc_textField_6.insets = new Insets(0, 0, 5, 0);
		gbc_textField_6.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_6.gridx = 6;
		gbc_textField_6.gridy = 8;
		addPermit.add(textField_6, gbc_textField_6);
		textField_6.setColumns(10);
		
		JButton sumbitBtn = new JButton("Submit");
		sumbitBtn.addActionListener(this);
		GridBagConstraints gbc_sumbitBtn = new GridBagConstraints();
		gbc_sumbitBtn.fill = GridBagConstraints.BOTH;
		gbc_sumbitBtn.insets = new Insets(0, 0, 0, 5);
		gbc_sumbitBtn.gridx = 1;
		gbc_sumbitBtn.gridy = 9;
		addPermit.add(sumbitBtn, gbc_sumbitBtn);
		
		JPanel recordWarning = new JPanel();
		tabbedPane.addTab("Record Warning", null, recordWarning, null);
		GridBagLayout gbl_recordWarning = new GridBagLayout();
		gbl_recordWarning.columnWidths = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_recordWarning.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_recordWarning.columnWeights = new double[]{0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, Double.MIN_VALUE};
		gbl_recordWarning.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		recordWarning.setLayout(gbl_recordWarning);
		
		JLabel lblRegistrationNumber_1 = new JLabel("Registration Number:");
		GridBagConstraints gbc_lblRegistrationNumber_1 = new GridBagConstraints();
		gbc_lblRegistrationNumber_1.gridwidth = 2;
		gbc_lblRegistrationNumber_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblRegistrationNumber_1.gridx = 1;
		gbc_lblRegistrationNumber_1.gridy = 2;
		recordWarning.add(lblRegistrationNumber_1, gbc_lblRegistrationNumber_1);
		
		textField_7 = new JTextField();
		GridBagConstraints gbc_textField_7 = new GridBagConstraints();
		gbc_textField_7.insets = new Insets(0, 0, 5, 5);
		gbc_textField_7.gridwidth = 8;
		gbc_textField_7.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_7.gridx = 5;
		gbc_textField_7.gridy = 2;
		recordWarning.add(textField_7, gbc_textField_7);
		textField_7.setColumns(10);
		
		JButton btnSubmitWarning = new JButton("Submit Warning");
		GridBagConstraints gbc_btnSubmitWarning = new GridBagConstraints();
		btnSubmitWarning.addActionListener(this);
		gbc_btnSubmitWarning.insets = new Insets(0, 0, 5, 5);
		gbc_btnSubmitWarning.gridx = 5;
		gbc_btnSubmitWarning.gridy = 4;
		recordWarning.add(btnSubmitWarning, gbc_btnSubmitWarning);
		
		textField_8 = new JTextField();
		GridBagConstraints gbc_textField_8 = new GridBagConstraints();
		gbc_textField_8.gridheight = 3;
		gbc_textField_8.gridwidth = 11;
		gbc_textField_8.fill = GridBagConstraints.BOTH;
		gbc_textField_8.gridx = 1;
		gbc_textField_8.gridy = 6;
		recordWarning.add(textField_8, gbc_textField_8);
		textField_8.setColumns(10);
		
		JPanel deleteWarning = new JPanel();
		tabbedPane.addTab("Delete Warning", null, deleteWarning, null);
		GridBagLayout gbl_deleteWarning = new GridBagLayout();
		gbl_deleteWarning.columnWidths = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_deleteWarning.rowHeights = new int[]{0, 0, 0, 0, 0, 0};
		gbl_deleteWarning.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, Double.MIN_VALUE};
		gbl_deleteWarning.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		deleteWarning.setLayout(gbl_deleteWarning);
		
		JLabel lblWarningNumber = new JLabel("Warning Number: ");
		GridBagConstraints gbc_lblWarningNumber = new GridBagConstraints();
		gbc_lblWarningNumber.insets = new Insets(0, 0, 5, 5);
		gbc_lblWarningNumber.gridx = 1;
		gbc_lblWarningNumber.gridy = 2;
		deleteWarning.add(lblWarningNumber, gbc_lblWarningNumber);
		
		textField_9 = new JTextField();
		GridBagConstraints gbc_textField_9 = new GridBagConstraints();
		gbc_textField_9.gridwidth = 9;
		gbc_textField_9.insets = new Insets(0, 0, 5, 5);
		gbc_textField_9.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_9.gridx = 5;
		gbc_textField_9.gridy = 2;
		deleteWarning.add(textField_9, gbc_textField_9);
		textField_9.setColumns(10);
		
		JButton btnSubmit = new JButton("Submit");
		GridBagConstraints gbc_btnSubmit = new GridBagConstraints();
		btnSubmit.addActionListener(this);
		gbc_btnSubmit.insets = new Insets(0, 0, 0, 5);
		gbc_btnSubmit.gridx = 6;
		gbc_btnSubmit.gridy = 4;
		deleteWarning.add(btnSubmit, gbc_btnSubmit);
		
		JPanel cancelPermit = new JPanel();
		tabbedPane.addTab("Cancel Permit", null, cancelPermit, null);
		GridBagLayout gbl_cancelPermit = new GridBagLayout();
		gbl_cancelPermit.columnWidths = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_cancelPermit.rowHeights = new int[]{0, 0, 0, 0, 0, 0};
		gbl_cancelPermit.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, Double.MIN_VALUE};
		gbl_cancelPermit.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		cancelPermit.setLayout(gbl_cancelPermit);
		
		JLabel lblPermitNumber = new JLabel("Permit Number: ");
		GridBagConstraints gbc_lblPermitNumber = new GridBagConstraints();
		gbc_lblPermitNumber .insets = new Insets(0, 0, 5, 5);
		gbc_lblPermitNumber .gridx = 1;
		gbc_lblPermitNumber .gridy = 2;
		cancelPermit.add(lblPermitNumber, gbc_lblPermitNumber );
		
		textField_10 = new JTextField();
		GridBagConstraints gbc_textField_10 = new GridBagConstraints();
		gbc_textField_10.gridwidth = 9;
		gbc_textField_10.insets = new Insets(0, 0, 5, 5);
		gbc_textField_10.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_10.gridx = 5;
		gbc_textField_10.gridy = 2;
		cancelPermit.add(textField_10, gbc_textField_10);
		textField_10.setColumns(10);
		
		JButton btnSubmitPermit = new JButton("Submit Permit");
		GridBagConstraints gbc_btnSubmitPermit = new GridBagConstraints();
		btnSubmitPermit.addActionListener(this);
		gbc_btnSubmitPermit.insets = new Insets(0, 0, 0, 5);
		gbc_btnSubmitPermit.gridx = 6;
		gbc_btnSubmitPermit.gridy = 4;
		cancelPermit.add(btnSubmitPermit, gbc_btnSubmitPermit);
		
		
		
		JPanel statusEnquiry = new JPanel();
		tabbedPane.addTab("Status Enquiry", null, statusEnquiry, null);
		
		JPanel modifyPermit = new JPanel();
		tabbedPane.addTab("Modify Permit", null, modifyPermit, null);
		GridBagLayout gbl_modifyPermit = new GridBagLayout();
		gbl_modifyPermit.columnWidths = new int[]{0, 0, 0, 0, 0, 0, 0, 0};
		gbl_modifyPermit.rowHeights = new int[] {30,30,30,30,30,30,30,30,30,30};
		gbl_modifyPermit.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, Double.MIN_VALUE};
		gbl_modifyPermit.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		modifyPermit.setLayout(gbl_modifyPermit);
		
		JLabel lblNameMod = new JLabel("Name: ");
		GridBagConstraints gbc_lblNameMod = new GridBagConstraints();
		gbc_lblNameMod.anchor = GridBagConstraints.WEST;
		gbc_lblNameMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblNameMod.gridx = 1;
		gbc_lblNameMod.gridy = 0;
		modifyPermit.add(lblNameMod , gbc_lblNameMod);
		
		textField_11 = new JTextField();
		GridBagConstraints gbc_textField_11 = new GridBagConstraints();
		gbc_textField_11.insets = new Insets(0, 0, 5, 0);
		gbc_textField_11.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_11.gridx = 6;
		gbc_textField_11.gridy = 0;
		modifyPermit.add(textField_11, gbc_textField_11);
		textField_11.setColumns(10);
		
		JLabel lblRegistrationNumberMod = new JLabel("Registration Number:");
		GridBagConstraints gbc_lblRegistrationNumberMod = new GridBagConstraints();
		gbc_lblRegistrationNumberMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblRegistrationNumberMod.gridx = 1;
		gbc_lblRegistrationNumberMod.gridy = 1;
		modifyPermit.add(lblRegistrationNumberMod, gbc_lblRegistrationNumberMod);
		
		textField_12 = new JTextField();
		GridBagConstraints gbc_textField_12 = new GridBagConstraints();
		gbc_textField_12.insets = new Insets(0, 0, 5, 0);
		gbc_textField_12.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_12.gridx = 6;
		gbc_textField_12.gridy = 1;
		modifyPermit.add(textField_12, gbc_textField_12);
		textField_12.setColumns(10);
		
		JLabel lblCarMakeMod = new JLabel("Car make:");
		GridBagConstraints gbc_lblCarMakeMod = new GridBagConstraints();
		gbc_lblCarMakeMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblCarMakeMod.anchor = GridBagConstraints.WEST;
		gbc_lblCarMakeMod.gridx = 1;
		gbc_lblCarMakeMod.gridy = 2;
		modifyPermit.add(lblCarMakeMod, gbc_lblCarMakeMod);
		
		textField_13 = new JTextField();
		GridBagConstraints gbc_textField_13 = new GridBagConstraints();
		gbc_textField_13.insets = new Insets(0, 0, 5, 0);
		gbc_textField_13.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_13.gridx = 6;
		gbc_textField_13.gridy = 2;
		modifyPermit.add(textField_13, gbc_textField_13);
		textField_13.setColumns(10);
		
		JLabel lblCarModelMod = new JLabel("Car model:");
		GridBagConstraints gbc_lblCarModelMod = new GridBagConstraints();
		gbc_lblCarModelMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblCarModelMod.anchor = GridBagConstraints.WEST;
		gbc_lblCarModelMod.gridx = 1;
		gbc_lblCarModelMod.gridy = 3;
		modifyPermit.add(lblCarModelMod, gbc_lblCarModelMod);
		
		textField_14 = new JTextField();
		GridBagConstraints gbc_textField_14 = new GridBagConstraints();
		gbc_textField_14.insets = new Insets(0, 0, 5, 0);
		gbc_textField_14.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_14.gridx = 6;
		gbc_textField_14.gridy = 3;
		modifyPermit.add(textField_14, gbc_textField_14);
		textField_14.setColumns(10);
		
		JLabel lblCarColorMod = new JLabel("Car color:");
		GridBagConstraints gbc_lblCarColorMod = new GridBagConstraints();
		gbc_lblCarColorMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblCarColorMod.anchor = GridBagConstraints.WEST;
		gbc_lblCarColorMod.gridx = 1;
		gbc_lblCarColorMod.gridy = 4;
		modifyPermit.add(lblCarColorMod, gbc_lblCarColorMod);
		
		textField_15 = new JTextField();
		GridBagConstraints gbc_textField_15 = new GridBagConstraints();
		gbc_textField_15.insets = new Insets(0, 0, 5, 0);
		gbc_textField_15.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_15.gridx = 6;
		gbc_textField_15.gridy = 4;
		modifyPermit.add(textField_15, gbc_textField_15);
		textField_15.setColumns(10);
		
		JLabel lblEnterPermitTypeMod = new JLabel("Enter Permit Type:");
		GridBagConstraints gbc_lblEnterPermitTypeMod = new GridBagConstraints();
		gbc_lblEnterPermitTypeMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblEnterPermitTypeMod.anchor = GridBagConstraints.WEST;
		gbc_lblEnterPermitTypeMod.gridx = 1;
		gbc_lblEnterPermitTypeMod.gridy = 5;
		modifyPermit.add(lblEnterPermitTypeMod, gbc_lblEnterPermitTypeMod);
		
		JComboBox comboBoxMod = new JComboBox();
		GridBagConstraints gbc_comboBoxMod = new GridBagConstraints();
		gbc_comboBoxMod.insets = new Insets(0, 0, 5, 0);
		gbc_comboBoxMod.fill = GridBagConstraints.HORIZONTAL;
		gbc_comboBoxMod.gridx = 6;
		gbc_comboBoxMod.gridy = 5;
		modifyPermit.add(comboBoxMod, gbc_comboBox);
		
		JLabel lblVisitDateMod = new JLabel("Visit Date:");
		GridBagConstraints gbc_lblVisitDateMod = new GridBagConstraints();
		gbc_lblVisitDateMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblVisitDateMod.anchor = GridBagConstraints.WEST;
		gbc_lblVisitDateMod.gridx = 1;
		gbc_lblVisitDateMod.gridy = 6;
		modifyPermit.add(lblVisitDateMod, gbc_lblVisitDateMod);
		
		textField_16 = new JTextField();
		GridBagConstraints gbc_textField_16 = new GridBagConstraints();
		gbc_textField_16.gridheight = 2;
		gbc_textField_16.insets = new Insets(0, 0, 5, 0);
		gbc_textField_16.fill = GridBagConstraints.BOTH;
		gbc_textField_16.gridx = 6;
		gbc_textField_16.gridy = 6;
		modifyPermit.add(textField_16, gbc_textField_16);
		textField_16.setColumns(10);
		
		JLabel lblHostNameMod = new JLabel("Host Name:");
		GridBagConstraints gbc_lblHostNameMod = new GridBagConstraints();
		gbc_lblHostNameMod.insets = new Insets(0, 0, 5, 5);
		gbc_lblHostNameMod.anchor = GridBagConstraints.WEST;
		gbc_lblHostNameMod.gridx = 1;
		gbc_lblHostNameMod.gridy = 8;
		modifyPermit.add(lblHostNameMod, gbc_lblHostNameMod);
		
		textField_17 = new JTextField();
		GridBagConstraints gbc_textField_17 = new GridBagConstraints();
		gbc_textField_17.insets = new Insets(0, 0, 5, 0);
		gbc_textField_17.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_17.gridx = 6;
		gbc_textField_17.gridy = 8;
		modifyPermit.add(textField_17, gbc_textField_17);
		textField_17.setColumns(10);
		
		JButton sumbitBtnMod = new JButton("Submit");
		sumbitBtnMod.addActionListener(this);
		GridBagConstraints gbc_sumbitBtnMod = new GridBagConstraints();
		gbc_sumbitBtnMod.fill = GridBagConstraints.BOTH;
		gbc_sumbitBtnMod.insets = new Insets(0, 0, 0, 5);
		gbc_sumbitBtnMod.gridx = 1;
		gbc_sumbitBtnMod.gridy = 9;
		modifyPermit.add(sumbitBtnMod, gbc_sumbitBtnMod);
		
		setVisible(true);
	}
	

		public void actionPerformed(ActionEvent e) {
		}
	
    

	@Override
	public void update(Observable arg0, Object arg1) {
		// TODO Auto-generated method stub
		
	}
}
