/* Generated by Together */

/**
 * For a description of Day visitors, follow hyperlink to the Administration use case for
 * issuing a new Day visitor permit.
 */
public class Day_visitor_permit extends Permit {
	/**
     * The name of the University member hosting the visit.
     */
    private String hostName;
    private Date activeDate;
    
    protected Day_visitor_permit(String permitHolder, String hostName, Vehicle_info firstVehicle, Date activeDate, Date issueDate) {
		super(permitHolder, firstVehicle, activeDate);
		
		this.activeDate = activeDate;
		this.hostName = hostName;
	}
    
    public String getHostName() {
    	return this.hostName;
    }
    
    public void changeActiveDate(Date newDate) {
    	this.activeDate = newDate;
    }
    
    public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public void setActiveDate(Date activeDate) {
		this.activeDate = activeDate;
	}

	public Date getActiveDate() {
    	return this.activeDate;
    }
}
