/* Generated by Together */

/**
 * For a description of Day visitors, follow hyperlink to the Administration use case for
 * issuing a new Day visitor permit.
 */
public class Day_visitor_permit extends Permit {
	/**
     * The name of the University member hosting the visit.
     */
    private String hostName;

    /**
     * The date that the visitor is visiting on - entry will be allowed on that date only.
     * @clientCardinality 1
     * @supplierCardinality 1
     * @label Visiting on
     * @link aggregation
     * @directed
     */
    private Date activeDate;
    
    protected Day_visitor_permit(String permitHolder, String hostName, Date activeDate) {
		super(permitHolder);
		
		this.hostName = hostName;
		this.activeDate = activeDate;
	}
    
    public Date getActiveDate() {
    	return this.activeDate;
    }
    
    public String getHostname() {
    	return this.hostName;
    }
}
