/* Generated by Together */

/**
 * For a description of Regular visitors, follow hyperlink to the Administration use case for
 * issuing a new Regular visitor permit.
 */
@SuppressWarnings("unused")
public class Regular_visitor_permit extends Permit {
	/**
     * The name of the University member hosting the visit.
     */
    private String hostName;

    /**
     * The date that the visit starts - entry will not be allowed before this date.
     * @label Starting on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private Date issueDate;

    /**
     * The date that the visit ends - entry will not be allowed after this date.
     * @label Ending on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private Date expiryDate;
    
    public Regular_visitor_permit(String permitHolder, String host, Date issue, Date expiry) {
		super(permitHolder);
		
		this.hostName = host;
		this.issueDate = issue;
		this.expiryDate = expiry;
	}
}
