/* Generated by Together */

/**
 * Each instance of Vehicle_info models an actual physical vehicle, so no two
 * instances may have the same registration number. There is no direct notation
 * for this. Instead the Vehicle list object collecting the Vehicles must
 * enforce it by checking new additions - the use of a HashTable in Vehicle_list
 * with the registration number as key is helpful with this.
 *
 * This class must contain at least the registration number, and may have any
 * other attributes that the University may from time to time find useful (such
 * as car make, model, colour...).
 */
@SuppressWarnings("unused")
public class Vehicle_info {
	/**
	 * The vehicle's registration number.
	 */
	private String regNo;
	private String colour;
	private String make;
	private String model;

	/**
	 * Each vehicle (and so each registration number) is associated with exactly one
	 * permit, which describes its authorization to enter the campus (or not!).
	 *
	 * This attribute references the permit associated with this vehicle. It allows
	 * the permit status of any vehicle to be accessed via the Vehicle_list knowing
	 * only the registration number - for example for barrier checks, recording
	 * warnings, and so on.
	 *
	 * Note that many vehicles may be associated with the same permit.
	 * 
	 * @supplierCardinality 1
	 * @clientCardinality 1..*
	 * @label Allowed entry by
	 * @directed
	 */
	private Permit lnkPermit;

	/**
	 * Get the permit
	 * 
	 * @return a permit
	 */
	public Permit getPermit() {
		return lnkPermit;
	}

	/**
	 * Set permit
	 * 
	 * @param lnkPermit the permit
	 */
	public void setPermit(Permit lnkPermit) {
		this.lnkPermit = lnkPermit;
	}

	/**
	 * Set the vehicle info empty constructor with registration number
	 * 
	 * @param reg
	 */
	public Vehicle_info(String reg) {
		this(reg, null, null, null);
	}

	/**
	 * Vehicle info parameter
	 * 
	 * @param reg    the registartion number
	 * @param colour the color number
	 * @param make   the maker of the car
	 * @param model  the model of the car
	 */
	public Vehicle_info(String reg, String colour, String make, String model) {
		this.regNo = reg;
		this.colour = colour;
		this.make = make;
		this.model = model;
	}

	/**
	 * get Color of the car
	 * 
	 * @return the car color
	 */
	public String getColour() {
		return colour;
	}

	/**
	 * Set colour of the car
	 * 
	 * @param colour the car colour
	 */
	public void setColour(String colour) {
		this.colour = colour;
	}

	/**
	 * Get the make of the car
	 * 
	 * @return the car make
	 */
	public String getMake() {
		return make;
	}

	/**
	 * Set the make of the car
	 * 
	 * @param make the car make
	 */
	public void setMake(String make) {
		this.make = make;
	}

	/**
	 * Get the model of the car
	 * 
	 * @return the car model
	 */
	public String getModel() {
		return model;
	}

	/**
	 * Set the model of the car
	 * 
	 * @param model car model
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * Set the registration number
	 * 
	 * @param regNo the registration number
	 */
	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	/**
	 * Get the registration Number
	 * 
	 * @return registration number
	 */
	public String getRegistration() {
		return this.regNo;
	}
}
